const grandBallroomEvents = [
  {
    eventId: 1,
    hallId: 1,
    name: 'Grand Ballroom Jazz Night',
    date: '2024-04-10',
    ticketPrice: 25,
    description: 'An enchanting night of jazz music and sophisticated ambiance.',
    featured: ['Jazz Ensemble', 'Guest Soloists'],
  },
  {
    eventId: 2,
    hallId: 1,
    name: 'Elegant Wedding Gala',
    date: '2024-05-20',
    ticketPrice: 50,
    description: 'Celebrate love and create timeless memories in a glamorous setting.',
    featured: ['Live Orchestra', 'Celebrity DJ'],
  },
  {
    eventId: 3,
    hallId: 1,
    name: 'Corporate Excellence Awards',
    date: '2024-06-15',
    ticketPrice: 35,
    description: 'An evening honoring outstanding achievements and corporate excellence.',
    featured: ['Keynote Speakers', 'Entertainment Presentations'],
  },
  {
    eventId: 4,
    hallId: 1,
    name: 'Fashion Elegance Showcase',
    date: '2024-07-25',
    ticketPrice: 30,
    description: 'Experience the latest trends and haute couture in a glamorous fashion showcase.',
    featured: ['Top Fashion Designers', 'Runway Models'],
  },
  {
    eventId: 5,
    hallId: 1,
    name: 'Annual Charity Gala',
    date: '2024-08-10',
    ticketPrice: 40,
    description: 'Support charitable causes while enjoying an evening of philanthropy and entertainment.',
    featured: ['Charity Ambassadors', 'Live Performances'],
  },
];

const artistryHavenEvents = [
  {
    eventId: 6,
    hallId: 2,
    name: 'Artistic Expression Symposium',
    date: '2024-09-05',
    ticketPrice: 25,
    description: 'Join artists from around the world in a symposium celebrating various forms of artistic expression.',
    featured: ['Renowned Painters', 'Sculptors', 'Digital Artists'],
  },
  {
    eventId: 7,
    hallId: 2,
    name: 'Culinary Arts Festival',
    date: '2024-10-15',
    ticketPrice: 40,
    description: 'Experience a fusion of flavors and culinary creativity in a festival dedicated to the culinary arts.',
    featured: ['Master Chefs', 'Food Critics'],
  },
  {
    eventId: 8,
    hallId: 2,
    name: 'Fashion Photography Exhibition',
    date: '2024-11-10',
    ticketPrice: 30,
    description: 'A showcase of stunning fashion photography capturing the essence of style and glamour.',
    featured: ['Fashion Photographers', 'Visual Artists'],
  },
  {
    eventId: 9,
    hallId: 2,
    name: 'Poetry and Prose Night',
    date: '2024-12-05',
    ticketPrice: 20,
    description: 'An evening of literary delight with poetry readings and expressive prose performances.',
    featured: ['Poetry Enthusiasts', 'Featured Writers'],
  },
  {
    eventId: 10,
    hallId: 2,
    name: 'Artisan Crafts Fair',
    date: '2025-01-20',
    ticketPrice: 15,
    description: 'Discover unique handmade crafts and artisanal creations in a vibrant crafts fair.',
    featured: ['Craftsmen', 'Artisans', 'Handmade Creators'],
  },
];

// For Sports Arena Deluxe (third hall with hallId 3)
const sportsArenaEvents = [
  {
    eventId: 11,
    hallId: 3,
    name: 'Sports Gala Championship',
    date: '2025-02-10',
    ticketPrice: 30,
    description: 'Witness an adrenaline-pumping sports championship featuring top athletes and teams.',
    featured: ['Champion Team', 'Contending Team'],
  },
  {
    eventId: 12,
    hallId: 3,
    name: 'Extreme Sports Extravaganza',
    date: '2025-03-15',
    ticketPrice: 35,
    description: 'Experience the thrill of extreme sports and daring performances in an action-packed extravaganza.',
    featured: ['Extreme Athletes', 'Stunt Performers'],
  },
  {
    eventId: 13,
    hallId: 3,
    name: 'Youth Soccer Tournament',
    date: '2025-04-20',
    ticketPrice: 25,
    description: 'Cheer for the next generation of soccer talents in an exciting youth soccer tournament.',
    featured: ['Junior Teams', 'Youth Athletes'],
  },
  {
    eventId: 14,
    hallId: 3,
    name: 'Basketball Showdown',
    date: '2025-05-25',
    ticketPrice: 28,
    description: 'Witness a high-intensity basketball showdown between rival teams vying for supremacy.',
    featured: ['Rival Teams A', 'Rival Teams B'],
  },
  {
    eventId: 15,
    hallId: 3,
    name: 'Gymnastics Spectacular',
    date: '2025-06-30',
    ticketPrice: 32,
    description: 'Marvel at the grace and skill of gymnasts in a spectacular gymnastics showcase.',
    featured: ['Gymnastic Stars', 'Acrobatic Ensembles'],
  },
];

// For Garden Pavilion (fourth hall with hallId 4)
const gardenPavilionEvents = [
  {
    eventId: 16,
    hallId: 4,
    name: 'Spring Garden Tea Party',
    date: '2025-07-05',
    ticketPrice: 15,
    description: 'Indulge in an enchanting tea party surrounded by the beauty of blooming spring gardens.',
    featured: ['Tea Tasting', 'Live Music'],
  },
  {
    eventId: 17,
    hallId: 4,
    name: 'Outdoor Yoga Retreat',
    date: '2025-08-10',
    ticketPrice: 18,
    description: 'Immerse yourself in nature with a rejuvenating outdoor yoga retreat in the tranquil garden setting.',
    featured: ['Yoga Gurus', 'Wellness Experts'],
  },
  {
    eventId: 18,
    hallId: 4,
    name: 'Botanical Art Workshop',
    date: '2025-09-15',
    ticketPrice: 20,
    description: 'Unleash your creativity in a botanical art workshop surrounded by vibrant flowers and plants.',
    featured: ['Artists', 'Botanists'],
  },
  {
    eventId: 19,
    hallId: 4,
    name: 'Summer Garden Concert',
    date: '2025-10-20',
    ticketPrice: 25,
    description: 'Enjoy an evening of live music and entertainment in the heart of a beautiful summer garden.',
    featured: ['Live Bands', 'Vocalists'],
  },
  {
    eventId: 20,
    hallId: 4,
    name: 'Harvest Festival Market',
    date: '2025-11-25',
    ticketPrice: 18,
    description: 'Explore a vibrant market celebrating the harvest season with local vendors and festive activities.',
    featured: ['Local Artisans', 'Farmers'],
  },
];

// For Tech Innovators Hub (fifth hall with hallId 5)
const techInnovatorsHubEvents = [
  {
    eventId: 21,
    hallId: 5,
    name: 'Tech Expo Showcase',
    date: '2025-12-01',
    ticketPrice: 30,
    description: 'Experience the latest in technology with cutting-edge innovations and tech showcases.',
    featured: ['Tech Companies', 'Innovators'],
  },
  {
    eventId: 22,
    hallId: 5,
    name: 'Startup Pitch Night',
    date: '2026-01-10',
    ticketPrice: 25,
    description: 'Witness exciting startup pitches and entrepreneurial ideas in a competitive pitch night event.',
    featured: ['Emerging Startups', 'Investor Panel'],
  },
  {
    eventId: 23,
    hallId: 5,
    name: 'Future Tech Symposium',
    date: '2026-02-15',
    ticketPrice: 35,
    description: 'Explore discussions and insights on the future of technology with industry experts and thought leaders.',
    featured: ['Tech Visionaries', 'Futurists'],
  },
  {
    eventId: 24,
    hallId: 5,
    name: 'Virtual Reality Experience Expo',
    date: '2026-03-20',
    ticketPrice: 40,
    description: 'Immerse yourself in the world of virtual reality with hands-on experiences and VR showcases.',
    featured: ['VR Developers', 'Experience Zones'],
  },
  {
    eventId: 25,
    hallId: 5,
    name: 'AI and Robotics Summit',
    date: '2026-04-25',
    ticketPrice: 45,
    description: 'Explore the advancements in artificial intelligence and robotics in an insightful summit event.',
    featured: ['AI Researchers', 'Robotics Engineers'],
  },
];

// For Cultural Heritage Hall (sixth hall with hallId 6)
const culturalHeritageHallEvents = [
  {
    eventId: 26,
    hallId: 6,
    name: 'Cultural Diversity Festival',
    date: '2026-05-01',
    ticketPrice: 20,
    description: 'Celebrate the rich tapestry of cultural diversity with performances, art, and cuisine from around the world.',
    featured: ['Cultural Ensembles', 'Traditional Artists'],
  },
  {
    eventId: 27,
    hallId: 6,
    name: 'International Film Showcase',
    date: '2026-06-10',
    ticketPrice: 25,
    description: 'Explore a curated selection of international films that showcase diverse storytelling and cinematic excellence.',
    featured: ['International Directors', 'Film Critics'],
  },
  {
    eventId: 28,
    hallId: 6,
    name: 'Heritage Crafts Exhibition',
    date: '2026-07-15',
    ticketPrice: 15,
    description: 'Discover traditional crafts and artisanal creations in an exhibition dedicated to cultural heritage.',
    featured: ['Craftsmen', 'Artisans'],
  },
  {
    eventId: 29,
    hallId: 6,
    name: 'Folklore Music Night',
    date: '2026-08-20',
    ticketPrice: 18,
    description: 'Immerse yourself in the melodies of traditional folklore music from different cultures.',
    featured: ['Folk Bands', 'Musical Storytellers'],
  },
  {
    eventId: 30,
    hallId: 6,
    name: 'Culinary Heritage Experience',
    date: '2026-09-25',
    ticketPrice: 22,
    description: 'Savor the flavors of cultural heritage with a culinary experience featuring traditional dishes.',
    featured: ['Culinary Experts', 'Traditional Cooks'],
  },
];

// For Luxe Lounge (seventh hall with hallId 7)
const luxeLoungeEvents = [
  {
    eventId: 31,
    hallId: 7,
    name: 'VIP Cocktail Soiree',
    date: '2026-10-01',
    ticketPrice: 50,
    description: 'Indulge in an exclusive VIP cocktail soiree with premium drinks, live music, and elegant ambiance.',
    featured: ['Celebrity Mixologists', 'Live Jazz Band'],
  },
  {
    eventId: 32,
    hallId: 7,
    name: 'High-End Fashion Show',
    date: '2026-11-10',
    ticketPrice: 55,
    description: 'Experience the epitome of style with a high-end fashion show featuring luxury brands and couture creations.',
    featured: ['Fashion Icons', 'Luxury Brands'],
  },
  {
    eventId: 33,
    hallId: 7,
    name: 'Exclusive Art Auction',
    date: '2026-12-15',
    ticketPrice: 60,
    description: 'Bid on exquisite artworks and collectibles in an exclusive art auction in a sophisticated lounge setting.',
    featured: ['Art Curators', 'Auction Specialists'],
  },
  {
    eventId: 34,
    hallId: 7,
    name: 'VIP Networking Gala',
    date: '2027-01-20',
    ticketPrice: 45,
    description: 'Connect with industry leaders and influencers in a VIP networking gala with curated experiences and discussions.',
    featured: ['VIP Guests', 'Industry Leaders'],
  },
  {
    eventId: 35,
    hallId: 7,
    name: 'Luxe Lounge Comedy Night',
    date: '2027-02-25',
    ticketPrice: 40,
    description: 'Enjoy an evening of laughter and entertainment with top-notch comedians in a luxurious lounge setting.',
    featured: ['Stand-Up Comedians', 'Humorists'],
  },
];

// For Theater Royale (eighth hall with hallId 8)
const theaterRoyaleEvents = [
  {
    eventId: 36,
    hallId: 8,
    name: 'Classic Shakespearean Play',
    date: '2027-03-01',
    ticketPrice: 35,
    description: 'Experience the timeless beauty of Shakespearean theater with a classic play in a grand theatrical setting.',
    featured: ['Shakespearean Actors', 'Theater Ensemble'],
  },
  {
    eventId: 37,
    hallId: 8,
    name: 'Broadway Musical Extravaganza',
    date: '2027-04-10',
    ticketPrice: 40,
    description: 'Be mesmerized by the magic of Broadway with a musical extravaganza featuring captivating performances.',
    featured: ['Broadway Stars', 'Musical Ensembles'],
  },
  {
    eventId: 38,
    hallId: 8,
    name: 'Dramatic Arts Festival',
    date: '2027-05-15',
    ticketPrice: 30,
    description: 'Celebrate the art of drama with a festival showcasing powerful theatrical performances and dramatic arts.',
    featured: ['Dramatic Artists', 'Playwrights'],
  },
  {
    eventId: 39,
    hallId: 8,
    name: 'Classic Film Screening',
    date: '2027-06-20',
    ticketPrice: 25,
    description: 'Relive the golden era of cinema with a screening of classic films in a majestic theater setting.',
    featured: ['Classic Movies', 'Film Historians'],
  },
  {
    eventId: 40,
    hallId: 8,
    name: 'Opera Night Spectacle',
    date: '2027-07-25',
    ticketPrice: 45,
    description: 'Indulge in the beauty of opera with a night of breathtaking performances by renowned opera singers.',
    featured: ['Opera Divas', 'Orchestra'],
  },
];

// For Adventure Pavilion (ninth hall with hallId 9)
const adventurePavilionEvents = [
  {
    eventId: 41,
    hallId: 9,
    name: 'Outdoor Adventure Fest',
    date: '2027-08-01',
    ticketPrice: 20,
    description: 'Embark on an exciting outdoor adventure festival with activities, workshops, and thrilling experiences.',
    featured: ['Outdoor Enthusiasts', 'Adventure Guides'],
  },
  {
    eventId: 42,
    hallId: 9,
    name: 'Camping and Stargazing Night',
    date: '2027-09-10',
    ticketPrice: 25,
    description: 'Spend a night under the stars with camping, stargazing, and nature-inspired activities in an adventure pavilion.',
    featured: ['Astronomy Experts', 'Nature Guides'],
  },
  {
    eventId: 43,
    hallId: 9,
    name: 'Extreme Sports Workshop',
    date: '2027-10-15',
    ticketPrice: 30,
    description: 'Learn the ins and outs of extreme sports with workshops and demonstrations by expert athletes.',
    featured: ['Extreme Athletes', 'Sports Coaches'],
  },
  {
    eventId: 44,
    hallId: 9,
    name: 'Mountain Climbing Challenge',
    date: '2027-11-20',
    ticketPrice: 35,
    description: 'Challenge yourself with a mountain climbing adventure and compete in a thrilling climbing challenge.',
    featured: ['Adventure Seekers', 'Climbing Enthusiasts'],
  },
  {
    eventId: 45,
    hallId: 9,
    name: 'Nature Photography Expedition',
    date: '2027-12-25',
    ticketPrice: 28,
    description: 'Capture the beauty of nature with a photography expedition led by experienced nature photographers.',
    featured: ['Nature Photographers', 'Photography Guides'],
  },
];

// For Skyline Terrace (tenth hall with hallId 10)
const skylineTerraceEvents = [
  {
    eventId: 46,
    hallId: 10,
    name: 'Rooftop Jazz Sunset',
    date: '2028-01-01',
    ticketPrice: 25,
    description: 'Savor the melodies of jazz music against the backdrop of a stunning sunset on a rooftop terrace.',
    featured: ['Jazz Ensemble', 'Saxophonist'],
  },
  {
    eventId: 47,
    hallId: 10,
    name: 'Elegant Rooftop Wedding',
    date: '2028-02-10',
    ticketPrice: 50,
    description: 'Exchange vows in an elegant rooftop wedding with panoramic views and a romantic ambiance.',
    featured: ['Wedding Couples', 'Guests'],
  },
  {
    eventId: 48,
    hallId: 10,
    name: 'Sunset Yoga and Meditation',
    date: '2028-03-15',
    ticketPrice: 18,
    description: 'Unwind with a session of yoga and meditation as the sun sets over the city skyline on a rooftop terrace.',
    featured: ['Yoga Instructors', 'Meditation Guides'],
  },
  {
    eventId: 49,
    hallId: 10,
    name: 'Rooftop Art and Wine Soiree',
    date: '2028-04-20',
    ticketPrice: 30,
    description: 'Indulge in an evening of art, wine, and conversation on a rooftop terrace with breathtaking views.',
    featured: ['Local Artists', 'Wine Tasting Experts'],
  },
  {
    eventId: 50,
    hallId: 10,
    name: 'Stargazing and Astronomy Night',
    date: '2028-05-25',
    ticketPrice: 22,
    description: 'Explore the cosmos with a stargazing and astronomy night on a rooftop terrace under the night sky.',
    featured: ['Astronomy Enthusiasts', 'Stargazing Guides'],
  },
];

// Array containing all the events for each hall
export const allEvents = [
  ...grandBallroomEvents,
  ...artistryHavenEvents,
  ...sportsArenaEvents,
  ...gardenPavilionEvents,
  ...techInnovatorsHubEvents,
  ...culturalHeritageHallEvents,
  ...luxeLoungeEvents,
  ...theaterRoyaleEvents,
  ...adventurePavilionEvents,
  ...skylineTerraceEvents,
];
